\ Compiler words that need special treatment during meta-compilation owing
\ to their use of POSTPONE

\ Compiler

HEX
\ IMMEDIATE for run-time speed
: R>ADDRESS   POSTPONE (LITERAL) 03FFFFFF ,  POSTPONE AND ;
IMMEDIATE COMPILING
DECIMAL

: DO,   POSTPONE 2>R ; COMPILING
: LOOP,   POSTPONE (LOOP)  POSTPONE IF  SWAP JOIN ; COMPILING
: +LOOP,   POSTPONE (+LOOP)  POSTPONE IF  SWAP JOIN ; COMPILING
: UNLOOP,   POSTPONE UNLOOP ; COMPILING


\ Data structures

: CREATE,   LINK,  POSTPONE (CREATE) ;
: LITERAL   POSTPONE (LITERAL) ALIGN  , ; IMMEDIATE COMPILING