\ Mass storage input/output words
\ Reuben Thomas   started 2/7/96

ALSO ASSEMBLER

0 1 $0 EXTRA-PRIMITIVE TOTAL-ARGS
1 1 $1 EXTRA-PRIMITIVE ARG-LEN
3 1 $2 EXTRA-PRIMITIVE ARG-COPY
0 1 $3 EXTRA-PRIMITIVE STDIN
0 1 $4 EXTRA-PRIMITIVE STDOUT
0 1 $5 EXTRA-PRIMITIVE STDERR
2 1 $6 EXTRA-PRIMITIVE OPEN_FILE
1 1 $7 EXTRA-PRIMITIVE CLOSE-FILE
3 2 $8 EXTRA-PRIMITIVE READ-FILE
3 2 $9 EXTRA-PRIMITIVE WRITE_FILE
\ FIXME: the 2s below are NATIVE-POINTER-CELLS, which we can't know at build time.
1 2 1+ $A EXTRA-PRIMITIVE FILE-POSITION
2 1+ 1 $B EXTRA-PRIMITIVE REPOSITION-FILE
1 1 $C EXTRA-PRIMITIVE FLUSH-FILE
2 1 $D EXTRA-PRIMITIVE RENAME_FILE
1 1 $E EXTRA-PRIMITIVE DELETE_FILE
1 2 1+ $F EXTRA-PRIMITIVE FILE-SIZE
2 1+ 1 $10 EXTRA-PRIMITIVE RESIZE-FILE
1 2 $11 EXTRA-PRIMITIVE FILE-STATUS
PREVIOUS

0 CONSTANT R/O
1 CONSTANT W/O
2 CONSTANT R/W

4 CONSTANT CREATE-FAM

8 CONSTANT BIN-MODE
: BIN  BIN-MODE OR ;

: OPEN-FILE   ( c-addr u fam -- fid ior )   -ROT SCRATCH-C0END SWAP OPEN_FILE ;
: WRITE-FILE   ( c-addr u fileid -- ior )   WRITE_FILE NIP ;
: RENAME-FILE   ( c-addr1 u1 c-addr2 u2 -- ior )   SCRATCH-C0END -ROT HERE 256 C0END HERE
   SWAP RENAME_FILE ;
: DELETE-FILE   ( c-addr u -- ior )   SCRATCH-C0END DELETE_FILE ;
: CREATE-FILE   ( adr u fam -- fid ior )   CREATE-FAM OR  OPEN-FILE ;
: ABSOLUTE-ARG   ( u1 -- c-addr u2 )
   TOTAL-ARGS OVER > IF \ u1
      SCRATCH TUCK 256 ARG-COPY
   ELSE
      DROP  0 0
   THEN ;