\ Bee assembler for pForth
\
\ (c) Reuben Thomas 2020
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

CR .( Bee assembler )


VOCABULARY ASSEMBLER  ALSO ASSEMBLER DEFINITIONS

: INLINE   ( char -- )   LAST >INFO 2 + C! ;

FORTH DEFINITIONS
INCLUDE" code.fs"
: END-CODE   ALIGN  PREVIOUS ;
ASSEMBLER DEFINITIONS

: OFFSET   ( from to -- offset )   >-< ;
: OFFSET,   ( to -- )   HERE SWAP OFFSET , ;

0 CONSTANT OP_CALL    1 CONSTANT OP_LITERAL
2 CONSTANT OP_OFFSET  3 CONSTANT OP_INSTRUCTION

: >OPCODE   ( operand type -- )   SWAP  2 LSHIFT  OR ;
: INST   CREATE OP_INSTRUCTION >OPCODE ,  DOES> @ , ;
: BRANCH-INST   CREATE OP_INSTRUCTION >OPCODE ,  DOES> @ ,  OFFSET, ;

: INSTS   SWAP 1+ SWAP DO  I INST  LOOP ;

: BCALL  OP_CALL >OPCODE , ;
: BPUSH   OP_LITERAL >OPCODE , ;
: BPUSHREL   HERE SWAP OFFSET 2 ARSHIFT  OP_OFFSET >OPCODE , ;

 7  0 INSTS BNOP     BNOT     BAND     BOR      BXOR     BLSHIFT  BRSHIFT  BARSHIFT
11  8 INSTS BPOP     BDUP     BROLL    XSWAP
12 BRANCH-INST BJUMP
13 BRANCH-INST BJUMPZ
15 14 INSTS BCALL    BRET
23 16 INSTS BLOAD    BSTORE   BLOAD1   BSTORE1  XLOAD2   XSTORE2  XLOAD4   XSTORE4
31 24 INSTS BNEGATE  BADD     BMUL     BDIVMOD  BUDIVMOD BEQ      BLT      BULT
36 32 INSTS BPUSHR   BPOPR    BDUPR    BCATCH   BTHROW

69 64 INSTS BGET_SP  BSET_SP  BGET_RP  BSET_RP  BGET_MEMORY BWORD_BYTES

130 128 INSTS BARGC BARGLEN BARGCOPY
133 131 INSTS BSTDIN BSTDOUT BSTDERR
135 134 INSTS BOPEN-FILE BCLOSE-FILE
137 136 INSTS BREAD-FILE BWRITE-FILE
139 138 INSTS BFILE-POSITION BREPOSITION-FILE
142 140 INSTS BFLUSH-FILE BRENAME-FILE BDELETE-FILE
144 143 INSTS BFILE-SIZE BRESIZE-FILE
145 INST   BFILE-STATUS

PREVIOUS DEFINITIONS
