\ Machine-dependent words (Bee)
\
\ (c) Reuben Thomas 2019-2020
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

\ Core compiler

: CALL   ( at from to -- )   >-< SWAP ! ;

: CALL,   HERE -  RAW, ;
: BRANCH,     3 RAW, ( FIXME: OP2_JUMPI 2 LSHIFT OP_LEVEL2 OR ) ;
: IF,   7 RAW, ( FIXME: OP2_JUMPZI 2 LSHIFT OP_LEVEL2 OR) ;

: @BRANCH   ( from -- to )   DUP @ 2 ARSHIFT + $FFFFFFFC AND ;
: !BRANCH   ( from to -- )   OVER - 2 LSHIFT  OVER @ $F AND  OR  SWAP ! ;
: COMPILE,   DUP >INFO 2 + C@  ?DUP IF  0 DO  DUP @ ,  CELL+  LOOP  DROP
   ELSE HERE - ,  THEN ;

: ADDR>LABEL   'FORTH - CELL/ ;
CHAR b CONSTANT BACKWARD
CHAR f CONSTANT FORWARD
CHAR n CONSTANT NONAME

: BEGIN   HERE  DUP BACKWARD .LABEL-DEF ; IMMEDIATE COMPILING
: AHEAD   HERE  DUP FORWARD .BRANCH  BRANCH, ; IMMEDIATE COMPILING
: IF   HERE  DUP FORWARD .IF  IF, ; IMMEDIATE COMPILING

: THEN   DUP FORWARD .LABEL-DEF  HERE !BRANCH ; IMMEDIATE COMPILING

: LINK, ;
: UNLINK,   $FF RAW,  .RET ( FIXME: BRET ) ; COMPILING
: LEAVE, ;
