\ Bee opcodes
\
\ (c) Reuben Thomas 2019-2020
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.


: OFFSET   ( from to -- offset )   >-< ;

0 CONSTANT OP_CALLI     1 CONSTANT OP_PUSHI
2 CONSTANT OP_PUSHRELI  3 CONSTANT OP_LEVEL2

0 CONSTANT OP2_JUMPI  1 CONSTANT OP2_JUMPZI
2 CONSTANT OP2_TRAP   3 CONSTANT OP2_INSN

3 CONSTANT OP_MASK
3 CONSTANT OP2_MASK

 0 CONSTANT INSN_NOP
 1 CONSTANT INSN_NOT
 2 CONSTANT INSN_AND
 3 CONSTANT INSN_OR
 4 CONSTANT INSN_XOR
 5 CONSTANT INSN_LSHIFT
 6 CONSTANT INSN_RSHIFT
 7 CONSTANT INSN_ARSHIFT

 8 CONSTANT INSN_POP
 9 CONSTANT INSN_DUP
10 CONSTANT INSN_SET
11 CONSTANT INSN_SWAP
12 CONSTANT INSN_JUMP
13 CONSTANT INSN_JUMPZ
14 CONSTANT INSN_CALL
15 CONSTANT INSN_RET

16 CONSTANT INSN_LOAD
17 CONSTANT INSN_STORE
18 CONSTANT INSN_LOAD1
19 CONSTANT INSN_STORE1
20 CONSTANT INSN_LOAD2
21 CONSTANT INSN_STORE2
22 CONSTANT INSN_LOAD4
23 CONSTANT INSN_STORE4

24 CONSTANT INSN_NEG
25 CONSTANT INSN_ADD
26 CONSTANT INSN_MUL
27 CONSTANT INSN_DIVMOD
28 CONSTANT INSN_UDIVMOD
29 CONSTANT INSN_EQ
30 CONSTANT INSN_LT
31 CONSTANT INSN_ULT

32 CONSTANT INSN_PUSHR
33 CONSTANT INSN_POPR
34 CONSTANT INSN_DUPR
35 CONSTANT INSN_CATCH
36 CONSTANT INSN_THROW
37 CONSTANT INSN_BREAK
38 CONSTANT INSN_WORD_BYTES
39 CONSTANT INSN_GET_M0

40 CONSTANT INSN_GET_MSIZE
41 CONSTANT INSN_GET_SSIZE
42 CONSTANT INSN_GET_SP
43 CONSTANT INSN_SET_SP
44 CONSTANT INSN_GET_DSIZE
45 CONSTANT INSN_GET_DP
46 CONSTANT INSN_SET_DP
47 CONSTANT INSN_GET_HANDLER_SP

48 CONSTANT #INSTRUCTIONS

: >OPCODE   ( operand type -- )   SWAP  CELLS  OR ;
: >OPCODE2   ( operand type -- )
   CELL 4 = IF
      SWAP  2 LSHIFT  OR  OP_LEVEL2  >OPCODE
   ELSE
      4 OR  >OPCODE
   THEN ;
