#!/bin/sh
# Install executor (used for Travis & AppVeyor build)

SUDO=sudo
if test "$1" = "--no-sudo"; then
    shift
    SUDO=""
fi

BUILD=$1

case $BUILD in
    beetle)
        cd $HOME
        # From https://gist.github.com/steinwaywhw/a4cd19cda655b8249d908261a62687f8
        # Authentication is needed to prevent exceeding API limits from Travis/AppVeyor
        if test "$GITHUB_TOKEN" != ""; then
            LATEST_RELEASE=`curl -H "Authorization: token $GITHUB_TOKEN" https://api.github.com/repos/rrthomas/beetle/releases/latest | grep tag_name | sed -e 's/.*tag_name": "\([^"]*\).*/\1/'`
        else
            LATEST_RELEASE=`curl https://api.github.com/repos/rrthomas/beetle/releases/latest | grep tag_name | sed -e 's/.*tag_name": "\([^"]*\).*/\1/'`
        fi
        LATEST_RELEASE_NUMBER=`echo $LATEST_RELEASE | sed -e s/^v//`
        FILE=beetle-$LATEST_RELEASE_NUMBER.tar.gz
        curl -L https://github.com/rrthomas/beetle/releases/download/$LATEST_RELEASE/$FILE -o $FILE
        tar zxf $FILE
        cd beetle-$LATEST_RELEASE_NUMBER
        ./configure --enable-silent-rules && make check && $SUDO make install
        ;;
    arm-riscos)
        cd src/\!pForth
        RPCEMU_VERSION=0.9.0
        DIR=rpcemu-$RPCEMU_VERSION
        FILE=$DIR.tar.gz
        curl -L http://www.4corn.co.uk/archive//roms/riscos3_71.zip -o roms.zip
        curl -L "http://www.marutan.net/rpcemu/cgi/download.php?sFName=$RPCEMU_VERSION/$FILE" -o $FILE
        sha256sum --check SHA256SUMS
        tar zxf $FILE
        unzip roms.zip
        mv risocs-3.71.rom $DIR/roms/rom # Typo in filename is intentional: it's mis-spelt in the zip!
        cd $DIR
        patch -p1 < ../rpcemu.patch
        cd src/qt5
        ./buildit.sh
        make
        ;;
    mit)
        cd $HOME
        git clone https://github.com/rrthomas/mit.git
        cd mit
        # Make install before make check so Python ctypes's find_library can find libmit
        ./bootstrap && ./configure --enable-silent-rules WORD_BYTES=4 && $SUDO make install && make check
        ;;
esac
