\ (c) Reuben Thomas 1995-2021
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

CR .( Extra primitives )

ALSO ASSEMBLER

\ Stack primitives
8 PRIMITIVES DUP SWAP OVER ROT -ROT TUCK NIP ?DUP

\ Memory primitives
1 PRIMITIVES +!

\ Arithmetic and logical primitives
7 PRIMITIVES > <> 0< 0> 0= 0<> U>
6 PRIMITIVES 1+ 1- CELL+ CELL- - >-<
CODE 2*   B1LSHIFT BEXIT END-CODE  1 INLINE
2 PRIMITIVES 2/ CELLS
CODE CELL/   B2/ B2/ BEXIT END-CODE  2 INLINE
6 PRIMITIVES /MOD / MOD MAX MIN ABS
2 PRIMITIVES 1LSHIFT 1RSHIFT
3 PRIMITIVES 0 1 -1
CODE TRUE   B-1 BEXIT END-CODE  1 INLINE
CODE FALSE   B0 BEXIT END-CODE  1 INLINE

\ Control primitives
3 PRIMITIVES J EXIT UNLOOP
2 PRIMITIVES THROW 'THROW!

\ System primitives
CODE BYE   B0 BHALT END-CODE  2 INLINE
1 PRIMITIVES LINK

PREVIOUS