\ Compiler

: R>ADDRESS ; IMMEDIATE COMPILING
: (POSTPONE)   R> R>ADDRESS ALIGNED  DUP CELL+ >R  @ CURRENT-COMPILE, ;
: (RELATIVE-POSTPONE)   R> R>ADDRESS ALIGNED DUP CELL+ >R  @ HERE - , ;


\ Data structures

: >BODY   2 CELLS + ;
: CREATE,  $01060C0B , CELL , ; \ LIT_PC_REL ( CELL ) LIT_0 SWAP JUMP
: (DOES>)   $030B  LAST  TUCK !  CELL+  R> R>ADDRESS @  OVER -  SWAP ! ;