\ These words are defined in compiler-asm.fs
DEFER .SKIP
DEFER .ALIGN
DEFER .CALIGN
DEFER .INT
DEFER .BYTE
DEFER .STRING
DEFER .PUSHI
DEFER .PUSHRELI
DEFER .PUSH
DEFER .LABEL
DEFER .LABEL-DEF
DEFER .BRANCH
DEFER .IF
DEFER .RET
DEFER .COMPILE-METHOD
DEFER .INLINE-COUNT
DEFER .CREATED-CODE