\ Compiler #4
\
\ (c) Reuben Thomas 1995-2019
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

: COLON   HEADER  TRUE SMUDGE  LINK,  ] ;
: :   BL WORD  COLON ;
: CURRENT?   ( wid xt n -- f )   2DROP  GET-CURRENT = ;
: PROVIDED?  ['] CURRENT? SELECT NIP ;
: [PROVIDED]   BL WORD PROVIDED? ; IMMEDIATE
: PROVIDE:
   BL WORD  DUP PROVIDED? IF
      DROP
      POSTPONE [ELSE]
   ELSE
      COLON
   THEN ;
: ;   UNLINK,  POSTPONE [  FALSE SMUDGE ; IMMEDIATE COMPILING
: :NONAME   ALIGN  0 ,  HERE LINK,  ] ;
: ;IMMEDIATE   POSTPONE ;  IMMEDIATE  LAST >COMPILE RELATIVE-LINK! ; IMMEDIATE COMPILING
