\ Compiler #2
\
\ (c) Reuben Thomas 1995-2016
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

: C"   [CHAR] " PARSE  POSTPONE CLITERAL ; IMMEDIATE COMPILING
: S"   [CHAR] " PARSE  S"B SWAP 2DUP 2>R  CMOVE  2R> ;
   :NONAME   [CHAR] " PARSE  POSTPONE SLITERAL ;IMMEDIATE

: ."   POSTPONE S"  POSTPONE TYPE ; IMMEDIATE COMPILING

: CHAR   BL WORD  CHAR+ C@ ;
: [CHAR]   CHAR  POSTPONE LITERAL ; IMMEDIATE COMPILING
