\ Compiler #4

: COLON   HEADER  TRUE SMUDGE  LINK,  ] ;
: :   BL WORD  COLON ;
: CURRENT?   ( wid xt n -- f )   2DROP  GET-CURRENT = ;
: PROVIDED?  ['] CURRENT? SELECT NIP ;
: [PROVIDED]   BL WORD PROVIDED? ; IMMEDIATE
: PROVIDE:
   BL WORD  DUP PROVIDED? IF
      DROP
      POSTPONE [ELSE]
   ELSE
      COLON
   THEN ;
: ;   UNLINK,  POSTPONE [  FALSE SMUDGE ; IMMEDIATE COMPILING
: :NONAME   ALIGN  0 ,  HERE LINK,  ] ;
\ FIXME: This is the only use for a separate compilation method
: ;IMMEDIATE   POSTPONE ;  IMMEDIATE  LAST >COMPILE ! ; IMMEDIATE COMPILING
