\ Control structures #2

: "CASE   POSTPONE CASE ; IMMEDIATE COMPILING
: "OF   1+ >R  POSTPONE 2OVER POSTPONE COMPARE POSTPONE 0= POSTPONE IF
  POSTPONE 2DROP  R> ; IMMEDIATE COMPILING
: "ENDOF   POSTPONE ENDOF ; IMMEDIATE COMPILING
: "ENDCASE   POSTPONE 2DROP  0 ?DO  POSTPONE THEN  LOOP ; IMMEDIATE COMPILING
