\ Control #1

PROVIDE: (LOOP)   R>  R> 1+  DUP R@ =  SWAP >R  SWAP >R ; [THEN]
PROVIDE: (+LOOP)   R> SWAP  R>  R@ OVER SWAP -  -ROT +  R@ OVER SWAP -
   SWAP >R  XOR 0<  SWAP >R ; [THEN]
PROVIDE: UNLOOP   R>  R> DROP R> DROP  >R ; [THEN]