\ (c) Reuben Thomas 2016-2019
\
\ The package is distributed under the GNU GPL version 3, or, at your
\ option, any later version.
\
\ THIS PROGRAM IS PROVIDED AS IS, WITH NO WARRANTY. USE IS AT THE USER’S
\ RISK.

\ Control structures #2

: WHILE   POSTPONE IF  1 ROLL ; IMMEDIATE COMPILING
: REPEAT   POSTPONE AGAIN  POSTPONE THEN ; IMMEDIATE COMPILING
: ELSE   POSTPONE AHEAD  1 ROLL  POSTPONE THEN ; IMMEDIATE COMPILING

VARIABLE 'NODE
VARIABLE 'LOOP
: NEW-NODE
   'NODE @ 'LOOP @
   HERE  CELL 1- INVERT AND
   DUP 'LOOP ! 'NODE ! ;
: TIE-NODE
   'LOOP @ FORWARD .LABEL-DEF
   'NODE @
   BEGIN
      DUP 'LOOP @ <> WHILE
      DUP @BRANCH SWAP  POSTPONE THEN
   REPEAT DROP
   'LOOP ! 'NODE ! ;
: I   POSTPONE R@ ; IMMEDIATE COMPILING
: LEAVE   LEAVE,  'LOOP @ FORWARD .BRANCH  HERE  'NODE  DUP @  HERE BRANCH, SWAP !BRANCH  ! ; IMMEDIATE COMPILING
: DO   NEW-NODE  DO,  POSTPONE BEGIN ; IMMEDIATE COMPILING
: ?DO   NEW-NODE  POSTPONE 2DUP DO, POSTPONE = POSTPONE IF
   POSTPONE LEAVE POSTPONE THEN  POSTPONE BEGIN ; IMMEDIATE COMPILING
: LOOP   LOOP,  TIE-NODE  END-LOOP, ; IMMEDIATE COMPILING
: +LOOP   +LOOP,  TIE-NODE  END-LOOP, ; IMMEDIATE COMPILING

: RECURSE   LAST COMPILE, ; IMMEDIATE COMPILING

: CASE   0 ; IMMEDIATE COMPILING
: OF   1+ >R  POSTPONE OVER POSTPONE = POSTPONE IF  POSTPONE DROP  R> ;
IMMEDIATE COMPILING
: ENDOF   >R  POSTPONE ELSE  R> ; IMMEDIATE COMPILING
: ENDCASE   POSTPONE DROP  0 ?DO  POSTPONE THEN  LOOP ; IMMEDIATE COMPILING
