\ Defining

: CREATE   BL WORD HEADER  CREATE, ;
INCLUDE" does.fs"

: VARIABLE   CREATE  CELL ALLOT ;
: CONSTANT   BL WORD HEADER  LINK,  POSTPONE LITERAL  UNLINK, ;
: VALUE   CREATE  ,  DOES>  @ ;
: VECTOR   CREATE  ,  DOES>  @EXECUTE ;
: TO   ' >BODY ! ;
   :NONAME   ' >BODY  <'FORTH  POSTPONE LITERAL  POSTPONE ! ;IMMEDIATE
